# Generated by Django 4.2.17 on 2025-06-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
